### ISSUE TITLE
Goosifying the functions with multiple reference returns 

### ISSUE THREAD

**Issue by ismailkuru** [tchajed/goose#40]
Hi, 

I am not sure if the following is what is expected for the multiple return functions. Suppose we have the following return
var a, b = MultFunc(x,y)
which is goosified roughly into the following

...
let a := ref_to type_of_a (MultFunc "x" "y") in 
let b := ref_to type_of_b (MultFunc "x" "y") in 
let ("0_ret", "1_ret") := MultFunc "x" "y" in 
 "a" <- type_of_a "0_ret" ;; "b" <- type_of_b "1_ret" 
....

where I guess the problem multiple function-call-evals for each return is buggy. If the declaration of return vars , i.e. "a"  and "b", is enforced, we can end up having the expected translation

var a type_of_a
var b type_of_b
a,b = MultFunc(x,y)
properly translates

**Comment by ismailkuru** [comment]
Yes, ":=" works properly.

**Comment by upamanyus** [comment]
I don't understand the bug. Do you have an example .go file that generates the kind of bad output you show?

I've been unable to come up with a concrete example because Goose rejects declarations with multiple variables like `var a, b uint64`, including the code `var a, b = multReturnTwo()`.
(the error is detected here: https://github.com/tchajed/goose/blob/ebec12b032b0fdedaa6d53adb7f7ac987105a549/goose.go#L1453-L1456)

The current tests that we have for multiple return are [here](https://github.com/tchajed/goose/blob/ebec12b032b0fdedaa6d53adb7f7ac987105a549/internal/examples/semantics/multiple_return.go), and look to me like they're translating OK.

**Comment by ismailkuru** [comment]
Yeah, now I realized that It is an error introduced by my manual changes. So, I cannot reproduce the error I claimed. 
Sorry for the distraction.
